# Generated by Django 3.1 on 2020-11-04 17:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='titulo')),
                ('descripcion', models.CharField(max_length=100, verbose_name='descripcion')),
                ('texto', models.TextField()),
                ('elige_tu_categoria', models.IntegerField(blank=True, choices=[(1, 'pasteles'), (2, 'Deportes'), (3, 'Ciencia'), (4, 'Clima'), (5, 'Pandemia'), (6, 'Programaciòn')], default=2)),
                ('fecha', models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 4, 17, 35, 59, 12194, tzinfo=utc))),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
            },
        ),
    ]
