# Generated by Django 3.1 on 2020-11-04 17:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('newtemas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temas',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 4, 17, 36, 46, 444778, tzinfo=utc)),
        ),
    ]
