# Generated by Django 3.1 on 2020-10-04 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newtemas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temas',
            name='autor',
        ),
    ]
