# Generated by Django 3.1 on 2020-10-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newtemas', '0002_remove_temas_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='temas',
            name='autor',
            field=models.CharField(default='Anonimo', max_length=50),
        ),
    ]
