# Generated by Django 3.1 on 2020-10-04 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newtemas', '0004_auto_20201004_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temas',
            old_name='autor',
            new_name='autores',
        ),
    ]
