# Generated by Django 3.1 on 2020-10-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newtemas', '0005_auto_20201004_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temas',
            name='autores',
        ),
        migrations.AddField(
            model_name='temas',
            name='descripcion',
            field=models.CharField(default=None, max_length=100, verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='temas',
            name='titulo',
            field=models.CharField(default='coloque el titulo', max_length=50),
        ),
    ]
