# Generated by Django 3.1 on 2020-11-01 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newtemas', '0007_auto_20201101_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='temas',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 1, 15, 7, 14, 446734)),
        ),
    ]
