# Generated by Django 3.1 on 2020-11-02 02:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newtemas', '0008_temas_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temas',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 1, 23, 33, 13, 533741)),
        ),
    ]
